CREATE DATABASE IF NOT EXISTS learnmate_ai;
USE learnmate_ai;

CREATE TABLE IF NOT EXISTS quizzes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  notes TEXT NOT NULL,
  difficulty VARCHAR(10) DEFAULT 'medium',
  questions JSON NOT NULL,
  score INT DEFAULT NULL,
  total_questions INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS question_sets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  notes TEXT NOT NULL,
  question_type VARCHAR(10) DEFAULT 'mixed',
  questions JSON NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
SELECT USER(), CURRENT_USER();
