import { useState } from 'react'
import './App.css'

const API_URL = 'http://localhost:5000/api'

const fallbackQuiz = (count, difficulty) => Array.from({ length: count }, (_, index) => ({
  question: `What is the most important idea in your notes? (Question ${index + 1})`,
  options: ['The main concept', 'A small detail', 'An unrelated idea', 'None of these'],
  correctAnswer: 'The main concept',
  difficulty,
}))

const fallbackQuestions = (count, type) => Array.from({ length: count }, (_, index) => ({
  question: `${type === 'Long Answer' ? 'Explain in detail' : 'Describe'} an important idea from your notes (Question ${index + 1}).`,
}))

async function request(path, body) {
  const response = await fetch(`${API_URL}${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) })
  if (!response.ok) throw new Error('The backend is unavailable.')
  return response.json()
}

function Logo({ setPage }) { return <button className="logo" onClick={() => setPage('home')}><span className="logo-mark">L</span>LearnMate <b>AI</b></button> }
function Button({ children, onClick, type = 'button' }) { return <button type={type} className="button" onClick={onClick}>{children}<span>→</span></button> }
function Header({ setPage }) { return <header><Logo setPage={setPage} /><nav><button onClick={() => setPage('home')}>Home</button><button onClick={() => setPage('quiz-generator')}>Quiz Generator</button><button onClick={() => setPage('question-generator')}>Question Generator</button></nav></header> }
function Layout({ setPage, children }) { return <div className="app"><Header setPage={setPage} />{children}<footer><Logo setPage={setPage} /><span>Simple tools for stronger understanding.</span></footer></div> }

function Home({ setPage }) { return <><main className="home"><div><p className="eyebrow">Your study companion</p><h1>Turn notes into<br /><em>knowledge.</em></h1><p className="lead">Paste your study notes, generate useful questions, and practice with a quiz made for you.</p><div className="home-actions"><Button onClick={() => setPage('quiz-generator')}>Generate a quiz</Button><button className="text-link" onClick={() => setPage('question-generator')}>Study questions →</button></div></div><div className="home-art"><div className="art-note"><small>LEARNMATE AI</small><h2>Biology<br /><em>notes</em></h2><i /><i /><i className="short" /><span>✦</span></div><div className="art-pill">Questions ready</div></div></main><section className="features"><p className="eyebrow">One simple workflow</p><h2>Everything you need to<br /><em>practice better.</em></h2><div className="feature-grid"><article><b>01</b><h3>Paste your notes</h3><p>Start with the material you already have.</p></article><article><b>02</b><h3>Generate questions</h3><p>Create a quiz or study questions in seconds.</p></article><article><b>03</b><h3>See your score</h3><p>Attempt the quiz and understand your result.</p></article></div></section></> }

function QuizGenerator({ setPage, setQuiz }) { const [notes, setNotes] = useState(''); const [count, setCount] = useState(5); const [difficulty, setDifficulty] = useState('Medium'); const [loading, setLoading] = useState(false); const generate = async (event) => { event.preventDefault(); setLoading(true); try { const data = await request('/quiz/generate', { notes, numberOfQuestions: count, difficulty }); setQuiz({ ...data, notes }); } catch { setQuiz({ notes, numberOfQuestions: Number(count), difficulty, questions: fallbackQuiz(Number(count), difficulty) }) } finally { setLoading(false); setPage('quiz') } }; return <main className="form-page"><p className="eyebrow">Quiz generator</p><h1>Build a quiz<br /><em>from your notes.</em></h1><form onSubmit={generate} className="study-form"><label>Study notes<textarea required value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Paste your notes or study content here..." /></label><div className="form-row"><label>Number of questions<select value={count} onChange={(event) => setCount(event.target.value)}>{[3, 5, 10].map((number) => <option key={number}>{number}</option>)}</select></label><label>Difficulty<select value={difficulty} onChange={(event) => setDifficulty(event.target.value)}><option>Easy</option><option>Medium</option><option>Hard</option></select></label></div><Button type="submit">{loading ? 'Generating...' : 'Generate quiz'}</Button></form></main> }

function Quiz({ quiz, setPage, setResult }) { const [answers, setAnswers] = useState({}); if (!quiz) return <QuizGenerator setPage={setPage} setQuiz={() => {}} />; const submit = async () => { const correct = quiz.questions.filter((question, index) => answers[index] === question.correctAnswer).length; const result = { ...quiz, correct, wrong: quiz.questions.length - correct, percentage: Math.round((correct / quiz.questions.length) * 100), answers }; setResult(result); try { await request('/quiz/save', { ...quiz, score: result.percentage }) } catch { /* The result remains available when MySQL is not configured. */ } setPage('result') }; return <main className="quiz-page"><div className="quiz-heading"><p className="eyebrow">Your quiz</p><h1>Show what<br /><em>you know.</em></h1><span>{quiz.questions.length} questions · {quiz.difficulty}</span></div><div className="questions">{quiz.questions.map((question, index) => <article className="question-card" key={question.question}><p className="question-number">Question {index + 1}</p><h2>{question.question}</h2><div className="options">{question.options.map((option, optionIndex) => <label className={answers[index] === option ? 'option selected' : 'option'} key={option}><input type="radio" name={`question-${index}`} checked={answers[index] === option} onChange={() => setAnswers({ ...answers, [index]: option })} /><span>{String.fromCharCode(65 + optionIndex)}</span>{option}</label>)}</div></article>)}</div><Button onClick={submit}>Submit quiz</Button></main> }

function Result({ result, setPage }) { return <main className="result"><p className="eyebrow">Quiz result</p><div className="score"><strong>{result?.percentage || 0}%</strong><span>{result?.correct || 0} correct out of {result?.questions?.length || 0}</span></div><h1>Keep going,<br /><em>you are learning.</em></h1><div className="result-stats"><span><b>{result?.questions?.length || 0}</b>Total questions</span><span><b>{result?.correct || 0}</b>Correct answers</span><span><b>{result?.wrong || 0}</b>Wrong answers</span></div><Button onClick={() => setPage('quiz-generator')}>Try another quiz</Button></main> }

function QuestionGenerator() { const [notes, setNotes] = useState(''); const [count, setCount] = useState(5); const [type, setType] = useState('Mixed'); const [questions, setQuestions] = useState(null); const [loading, setLoading] = useState(false); const generate = async (event) => { event.preventDefault(); setLoading(true); try { const data = await request('/questions/generate', { notes, numberOfQuestions: count, questionType: type }); setQuestions(data.questions) } catch { setQuestions(fallbackQuestions(Number(count), type)) } finally { setLoading(false) } }; const save = async () => { try { await request('/questions/save', { notes, numberOfQuestions: count, questionType: type, questions }) } catch { window.alert('Question set is ready. Connect MySQL to save it.') } }; return <main className="form-page"><p className="eyebrow">Question generator</p><h1>Make study<br /><em>questions.</em></h1><form onSubmit={generate} className="study-form"><label>Study notes<textarea required value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Paste your notes or study content here..." /></label><div className="form-row"><label>Number of questions<select value={count} onChange={(event) => setCount(event.target.value)}>{[3, 5, 10].map((number) => <option key={number}>{number}</option>)}</select></label><label>Question type<select value={type} onChange={(event) => setType(event.target.value)}><option>Short Answer</option><option>Long Answer</option><option>Mixed</option></select></label></div><Button type="submit">{loading ? 'Generating...' : 'Generate questions'}</Button></form>{questions && <section className="generated"><div className="generated-heading"><h2>Your study questions</h2><button className="text-link" onClick={save}>Save to MySQL</button></div>{questions.map((item, index) => <div className="generated-question" key={item.question}><b>{String(index + 1).padStart(2, '0')}</b><p>{item.question}</p></div>)}</section>}</main> }

function App() { const [page, setPage] = useState('home'); const [quiz, setQuiz] = useState(null); const [result, setResult] = useState(null); let content; if (page === 'home') content = <Home setPage={setPage} />; if (page === 'quiz-generator') content = <QuizGenerator setPage={setPage} setQuiz={setQuiz} />; if (page === 'quiz') content = <Quiz quiz={quiz} setPage={setPage} setResult={setResult} />; if (page === 'result') content = <Result result={result} setPage={setPage} />; if (page === 'question-generator') content = <QuestionGenerator />; return <Layout setPage={setPage}>{content}</Layout> }
export default App
