import { useState } from 'react'
import './App.css'

const API_URL = 'http://localhost:5000/api'

async function request(path, body) {
  const isForm = body instanceof FormData
  let response
  try {
    response = await fetch(`${API_URL}${path}`, { method: 'POST', ...(isForm ? {} : { headers: { 'Content-Type': 'application/json' } }), body: isForm ? body : JSON.stringify(body) })
  } catch {
    throw new Error('Cannot connect to the backend at http://localhost:5000. Start the backend and try again.')
  }
  if (!response.ok) {
    const error = await response.json().catch(() => ({}))
    throw new Error(error.message || 'The backend is unavailable.')
  }
  return response.json()
}

function Logo({ setPage }) { return <button className="logo" onClick={() => setPage('home')}><span className="logo-mark">L</span>LearnMate <b>AI</b></button> }
function Button({ children, onClick, type = 'button' }) { return <button type={type} className="button" onClick={onClick}>{children}<span>→</span></button> }
function Header({ setPage, user, onLogout }) { return <header><Logo setPage={setPage} /><nav><button onClick={() => setPage('home')}>Home</button><button onClick={() => setPage('quiz-generator')}>Quiz Generator</button><button onClick={() => setPage('question-generator')}>Question Generator</button></nav><div className="account-actions">{user ? <><span className="user-name">Hi, {user.name}</span><button className="account-link" onClick={onLogout}>Log out</button></> : <><button className="account-link" onClick={() => setPage('login')}>Log in</button><button className="account-button" onClick={() => setPage('register')}>Register</button></>}</div></header> }
function Layout({ setPage, user, onLogout, children }) { return <div className="app"><Header setPage={setPage} user={user} onLogout={onLogout} />{children}<footer><Logo setPage={setPage} /><span>Simple tools for stronger understanding.</span></footer></div> }

function Auth({ mode, setPage, onLogin }) { const register = mode === 'register'; const submit = (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); onLogin({ name: register ? form.get('name') : form.get('email').split('@')[0] }); setPage('home') }; return <main className="auth-page"><div className="auth-box"><button className="back-link" onClick={() => setPage('home')}>← Back home</button><p className="eyebrow">{register ? 'Create your account' : 'Welcome back'}</p><h1>{register ? 'Start learning.' : 'Log in to learn.'}</h1><p className="lead">{register ? 'Save your quizzes and keep your study workflow in one place.' : 'Enter your details to continue your study session.'}</p><form onSubmit={submit} className="auth-form">{register && <label>Full name<input name="name" required placeholder="Alex Morgan" /></label>}<label>Email address<input name="email" type="email" required placeholder="you@example.com" /></label><label>Password<input name="password" type="password" required minLength="6" placeholder="At least 6 characters" /></label><Button type="submit">{register ? 'Create account' : 'Log in'}</Button></form><button className="text-link" onClick={() => setPage(register ? 'login' : 'register')}>{register ? 'Already registered? Log in' : 'Need an account? Register'}</button></div></main> }

function Attachments({ files, setFiles }) { const addFiles = (event) => { const selected = Array.from(event.target.files || []); selected.forEach((file) => console.log('[FILE SELECTED]', { filename: file.name, type: file.type || 'unknown', size: file.size })); setFiles([...files, ...selected]); event.target.value = '' }; const removeFile = (index) => setFiles(files.filter((_, fileIndex) => fileIndex !== index)); return <div className="attachment-area"><label className="attachment-button"><input type="file" multiple accept=".pdf,.docx,.txt,image/*" onChange={addFiles} /><span>＋</span> Add photos or files</label><small>Images, PDF, DOCX, or TXT</small>{files.length > 0 && <div className="file-list">{files.map((file, index) => <div className="file-item" key={`${file.name}-${index}`}><span>{file.type.startsWith('image/') ? '▧' : '▤'}</span><strong>{file.name}</strong><button type="button" onClick={() => removeFile(index)} aria-label={`Remove ${file.name}`}>×</button></div>)}</div>}</div> }

function Home({ setPage }) { return <><main className="home"><div><p className="eyebrow">Your study companion</p><h1>Turn notes into<br /><em>knowledge.</em></h1><p className="lead">Paste your study notes, generate useful questions, and practice with a quiz made for you.</p><div className="home-actions"><Button onClick={() => setPage('quiz-generator')}>Generate a quiz</Button><button className="text-link" onClick={() => setPage('question-generator')}>Study questions →</button></div></div><div className="home-art"><div className="art-note"><small>LEARNMATE AI</small><h2>Biology<br /><em>notes</em></h2><i /><i /><i className="short" /><span>✦</span></div><div className="art-pill">Questions ready</div></div></main><section className="features"><p className="eyebrow">One simple workflow</p><h2>Everything you need to<br /><em>practice better.</em></h2><div className="feature-grid"><article><b>01</b><h3>Paste your notes</h3><p>Start with the material you already have.</p></article><article><b>02</b><h3>Generate questions</h3><p>Create a quiz or study questions in seconds.</p></article><article><b>03</b><h3>See your score</h3><p>Attempt the quiz and understand your result.</p></article></div></section></> }

function QuizGenerator({ setPage, setQuiz }) { const [notes, setNotes] = useState(''); const [files, setFiles] = useState([]); const [count, setCount] = useState(5); const [difficulty, setDifficulty] = useState('Medium'); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const generate = async (event) => { event.preventDefault(); setLoading(true); setError(''); const form = new FormData(); form.append('notes', notes); form.append('numberOfQuestions', count); form.append('difficulty', difficulty); files.forEach((file) => form.append('files', file)); console.log('[UPLOAD] files sent:', files.length); try { const data = await request('/quiz/generate', form); const generatedQuiz = { ...data, notes: data.notes || notes }; const savedQuiz = await request('/quiz/save', { ...generatedQuiz, numberOfQuestions: Number(data.numberOfQuestions || count), score: null }); setQuiz({ ...generatedQuiz, id: savedQuiz.id }); setPage('quiz') } catch (requestError) { setError(requestError.message) } finally { setLoading(false) } }; return <main className="form-page"><p className="eyebrow">Quiz generator</p><h1>Build a quiz<br /><em>from your notes.</em></h1><form onSubmit={generate} className="study-form"><label>Study notes<textarea required={files.length === 0} value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Paste your notes or study content here..." /></label><Attachments files={files} setFiles={setFiles} />{error && <p className="form-error">{error}</p>}<div className="form-row"><label>Number of questions<select value={count} onChange={(event) => setCount(event.target.value)}>{[3, 5, 10].map((number) => <option key={number}>{number}</option>)}</select></label><label>Difficulty<select value={difficulty} onChange={(event) => setDifficulty(event.target.value)}><option>Easy</option><option>Medium</option><option>Hard</option></select></label></div><Button type="submit">{loading ? 'Reading material...' : 'Generate quiz'}</Button></form></main> }

function Quiz({ quiz, setPage, setResult }) { const [answers, setAnswers] = useState({}); if (!quiz) return <QuizGenerator setPage={setPage} setQuiz={() => {}} />; const submit = async () => { const correct = quiz.questions.filter((question, index) => answers[index] === question.correctAnswer).length; const result = { ...quiz, correct, wrong: quiz.questions.length - correct, percentage: Math.round((correct / quiz.questions.length) * 100), answers }; setResult(result); try { await request('/quiz/save', quiz.id ? { id: quiz.id, score: result.percentage } : { ...quiz, numberOfQuestions: quiz.questions.length, score: result.percentage }) } catch { /* The result remains available when MySQL is not configured. */ } setPage('result') }; return <main className="quiz-page"><div className="quiz-heading"><p className="eyebrow">Your quiz</p><h1>Show what<br /><em>you know.</em></h1><span>{quiz.questions.length} questions · {quiz.difficulty}</span></div><section className="generated"><h2>Extracted study content</h2><pre>{quiz.extractedContent || quiz.notes}</pre></section><div className="questions">{quiz.questions.map((question, index) => <article className="question-card" key={question.question}><p className="question-number">Question {index + 1}</p><h2>{question.question}</h2><div className="options">{question.options.map((option, optionIndex) => <label className={answers[index] === option ? 'option selected' : 'option'} key={option}><input type="radio" name={`question-${index}`} checked={answers[index] === option} onChange={() => setAnswers({ ...answers, [index]: option })} /><span>{String.fromCharCode(65 + optionIndex)}</span>{option}</label>)}</div></article>)}</div><Button onClick={submit}>Submit quiz</Button></main> }

function Result({ result, setPage }) { return <main className="result"><p className="eyebrow">Quiz result</p><div className="score"><strong>{result?.percentage || 0}%</strong><span>{result?.correct || 0} correct out of {result?.questions?.length || 0}</span></div><h1>Keep going,<br /><em>you are learning.</em></h1><div className="result-stats"><span><b>{result?.questions?.length || 0}</b>Total questions</span><span><b>{result?.correct || 0}</b>Correct answers</span><span><b>{result?.wrong || 0}</b>Wrong answers</span></div><section className="answer-review"><h2>Answer review</h2>{result?.questions?.map((question, index) => { const answer = result.answers?.[index]; const correct = answer === question.correctAnswer; return <article className={correct ? 'review-item correct' : 'review-item incorrect'} key={`${question.question}-${index}`}><b>Question {index + 1}: {correct ? 'Correct' : 'Incorrect'}</b><p>Your answer: {answer || 'Not answered'}</p>{!correct && <p>Correct answer: {question.correctAnswer}</p>}</article> })}</section><Button onClick={() => setPage('quiz-generator')}>Try another quiz</Button></main> }

function QuestionGenerator() { const [notes, setNotes] = useState(''); const [files, setFiles] = useState([]); const [count, setCount] = useState(5); const [type, setType] = useState('Mixed'); const [questions, setQuestions] = useState(null); const [source, setSource] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const generate = async (event) => { event.preventDefault(); setLoading(true); setError(''); const form = new FormData(); form.append('notes', notes); form.append('numberOfQuestions', count); form.append('questionType', type); files.forEach((file) => form.append('files', file)); try { const data = await request('/questions/generate', form); await request('/questions/save', { notes: data.notes || notes, numberOfQuestions: Number(data.numberOfQuestions || count), difficulty: type, questions: data.questions }); setQuestions(data.questions); setSource(data.extractedContent || data.notes || '') } catch (requestError) { setError(requestError.message) } finally { setLoading(false) } }; return <main className="form-page"><p className="eyebrow">Question generator</p><h1>Make study<br /><em>questions.</em></h1><form onSubmit={generate} className="study-form"><label>Study notes<textarea required={files.length === 0} value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Paste your notes or study content here..." /></label><Attachments files={files} setFiles={setFiles} />{error && <p className="form-error">{error}</p>}<div className="form-row"><label>Number of questions<select value={count} onChange={(event) => setCount(event.target.value)}>{[3, 5, 10].map((number) => <option key={number}>{number}</option>)}</select></label><label>Question type<select value={type} onChange={(event) => setType(event.target.value)}><option>Short Answer</option><option>Long Answer</option><option>Mixed</option></select></label></div><Button type="submit">{loading ? 'Reading material...' : 'Generate questions'}</Button></form>{source && <section className="generated"><h2>Extracted study content</h2><pre>{source}</pre></section>}{questions && <section className="generated"><div className="generated-heading"><h2>Your study questions</h2><span>Saved to MySQL</span></div>{questions.map((item, index) => <div className="generated-question" key={item.question}><b>{String(index + 1).padStart(2, '0')}</b><p>{item.question}</p></div>)}</section>}</main> }

function App() { const [page, setPage] = useState('home'); const [quiz, setQuiz] = useState(null); const [result, setResult] = useState(null); const [user, setUser] = useState(null); let content; if (page === 'home') content = <Home setPage={setPage} />; if (page === 'login' || page === 'register') content = <Auth mode={page} setPage={setPage} onLogin={setUser} />; if (page === 'quiz-generator') content = <QuizGenerator setPage={setPage} setQuiz={setQuiz} />; if (page === 'quiz') content = <Quiz quiz={quiz} setPage={setPage} setResult={setResult} />; if (page === 'result') content = <Result result={result} setPage={setPage} />; if (page === 'question-generator') content = <QuestionGenerator />; return <Layout setPage={setPage} user={user} onLogout={() => setUser(null)}>{content}</Layout> }
export default App
