import { useState } from 'react'
import './Dashboard.css'

const navItems = [
  ['âŒ‚', 'Dashboard'], ['â–£', 'My Notes'], ['â†‘', 'Upload Notes'], ['âœ¦', 'Summaries'],
  ['â–¤', 'Flashcards'], ['?', 'Quizzes'], ['â—·', 'Study Planner'], ['â—Œ', 'AI Chat'],
  ['â†—', 'Progress'], ['âš™', 'Settings'], ['â†ª', 'Logout'],
]

const notes = [
  ['Data Structures', 'Computer Science', 'PDF', 'Oct 14, 2024'],
  ['Database Management', 'Information Systems', 'DOCX', 'Oct 11, 2024'],
  ['Web Technology', 'Computer Science', 'PDF', 'Oct 08, 2024'],
  ['Computer Networks', 'Networking', 'TXT', 'Oct 05, 2024'],
]

const quizzes = [['Data Structures Quiz', 'Computer Science', '8/10', 'Oct 14'], ['SQL Fundamentals', 'Database Management', '9/10', 'Oct 11'], ['HTML & CSS Basics', 'Web Technology', '7/10', 'Oct 08']]
const plans = [['Review linked lists', 'Today, 10:00 AM', 'In progress'], ['Practice SQL joins', 'Today, 3:30 PM', 'Up next'], ['Read network protocols', 'Tomorrow, 9:00 AM', 'Planned']]
const summaries = [['Data Structures', 'A focused overview of arrays, linked lists, stacks, and queues, with examples of when to use each structure.'], ['Database Management', 'Key concepts in relational databases, including normalization, primary keys, and efficient SQL queries.'], ['Web Technology', 'The foundations of modern web apps: semantic HTML, responsive CSS, and the role of JavaScript in the browser.']]
const flashcards = [['What is a stack data structure?', 'A linear data structure that follows the Last In, First Out (LIFO) principle.'], ['What does normalization reduce?', 'Normalization reduces data redundancy and improves data integrity in a relational database.']]

function DashboardLogo({ onHome }) { return <button className="dashboard-logo" onClick={onHome}><span className="dashboard-logo-mark">L</span><span>LearnMate <b>AI</b></span></button> }
function Button({ children, variant = 'primary', onClick }) { return <button className={`dash-button ${variant}`} onClick={onClick}>{children}</button> }
function ProgressBar({ value }) { return <div className="progress-track"><span style={{ width: `${value}%` }} /></div> }
function PageTitle({ eyebrow, title, text, action }) { return <div className="page-title"><div><p className="dash-eyebrow">{eyebrow}</p><h1>{title}</h1>{text && <p className="page-description">{text}</p>}</div>{action}</div> }
function StatCard({ icon, label, value, detail, tone }) { return <article className="stat-card"><span className={`stat-icon ${tone}`}>{icon}</span><p>{label}</p><strong>{value}</strong><small>{detail}</small></article> }
function NotesTable({ compact = false }) { return <div className="table-wrap"><table><thead><tr><th>Note</th><th>Subject</th><th>Type</th><th>Uploaded</th><th>Action</th></tr></thead><tbody>{notes.map(([title, subject, type, date]) => <tr key={title}><td><span className="file-icon">{type === 'PDF' ? 'P' : 'D'}</span><strong>{title}</strong></td><td>{subject}</td><td><span className="type-pill">{type}</span></td><td>{date}</td><td><button className="table-action">{compact ? 'View' : 'View'}</button>{!compact && <button className="table-action delete">Delete</button>}</td></tr>)}</tbody></table></div> }

function Overview({ navigate }) {
  return <><PageTitle eyebrow="Your learning space" title="Welcome back, Student! ðŸ‘‹" text="Ready to learn smarter today?" action={<Button onClick={() => navigate('Upload Notes')}>â†‘ &nbsp; Upload Notes</Button>} /><div className="stats-grid"><StatCard icon="â–£" label="Notes Uploaded" value="12" detail="+2 this week" tone="coral" /><StatCard icon="âœ“" label="Quizzes Completed" value="8" detail="80% average score" tone="mint" /><StatCard icon="â—·" label="Study Hours" value="24h" detail="+4h this week" tone="yellow" /><StatCard icon="â†—" label="Learning Progress" value="78%" detail="Keep it going" tone="blue" /></div><div className="overview-grid"><section className="dashboard-panel notes-panel"><div className="panel-header"><div><p className="dash-eyebrow">Keep your library close</p><h2>Recent notes</h2></div><button className="inline-link" onClick={() => navigate('My Notes')}>View all â†’</button></div><NotesTable compact /></section><section className="dashboard-panel quiz-panel"><div className="panel-header"><div><p className="dash-eyebrow">Test your knowledge</p><h2>Recent quiz results</h2></div><button className="inline-link" onClick={() => navigate('Quizzes')}>Take a quiz â†’</button></div><div className="result-list">{quizzes.map(([name, subject, score, date]) => <div className="result-item" key={name}><span className="result-badge">âœ“</span><div><strong>{name}</strong><small>{subject} Â· {date}</small></div><b>{score}</b></div>)}</div></section></div><section className="dashboard-panel plan-panel"><div className="panel-header"><div><p className="dash-eyebrow">Make today count</p><h2>Upcoming study plan</h2></div><button className="inline-link" onClick={() => navigate('Study Planner')}>Open planner â†’</button></div><div className="plan-list">{plans.map(([topic, time, status]) => <div className="plan-item" key={topic}><span className="plan-dot" /><div><strong>{topic}</strong><small>{time}</small></div><span className={`status ${status.toLowerCase().replace(' ', '-')}`}>{status}</span></div>)}</div></section></>
}

function UploadPage() { return <><PageTitle eyebrow="Build your library" title="Upload Your Notes" text="Bring your study material into one focused space. LearnMate will help you make more of every page." /><section className="upload-panel"><div className="upload-symbol">â†‘</div><h2>Drop your notes here</h2><p>or choose a file from your device</p><Button>Choose File</Button><small>Supported formats: <strong>PDF, DOCX, TXT</strong></small></section><div className="selected-file"><span className="file-icon">P</span><div><strong>data-structures-notes.pdf</strong><small>2.4 MB Â· Ready to upload</small></div><span className="ready">Ready</span><Button>Upload</Button></div></> }
function NotesPage() { return <><PageTitle eyebrow="Your library" title="My Notes" text="All your study material, organized and ready when you are." action={<Button>â†‘ &nbsp; Upload Notes</Button>} /><div className="filter-row"><div className="search-box">âŒ• <input placeholder="Search your notes..." /></div><select defaultValue="all"><option value="all">All subjects</option><option>Computer Science</option><option>Networking</option></select></div><section className="dashboard-panel"><NotesTable /></section></> }
function SummariesPage() { return <><PageTitle eyebrow="Make it click" title="Summaries" text="Quick, clear overviews of the topics you are learning." /><div className="filter-row"><div className="search-box">âŒ• <input placeholder="Search summaries..." /></div><button className="filter-button">All subjectsâŒ„</button></div><div className="summary-grid">{summaries.map(([title, text]) => <article className="summary-card" key={title}><span className="summary-card-icon">âœ¦</span><p className="dash-eyebrow">AI summary Â· 4 min read</p><h2>{title}</h2><p>{text}</p><button className="inline-link">Read Summary â†’</button></article>)}</div></> }
function FlashcardsPage() { const [index, setIndex] = useState(0); const [flipped, setFlipped] = useState(false); const [question, answer] = flashcards[index]; return <><PageTitle eyebrow="Practice makes progress" title="Flashcards" text="Review key ideas and make your memory work for you." /><div className="flashcard-layout"><div className={`flashcard ${flipped ? 'flipped' : ''}`}><p className="dash-eyebrow">Data Structures Â· Card {index + 1} of {flashcards.length}</p><h2>{flipped ? answer : question}</h2><span>{flipped ? 'Answer' : 'Question'}</span></div><div className="flashcard-controls"><Button variant="secondary" onClick={() => { setIndex((index - 1 + flashcards.length) % flashcards.length); setFlipped(false) }}>â† &nbsp; Previous</Button><Button onClick={() => setFlipped(!flipped)}>â†» &nbsp; Flip Card</Button><Button variant="secondary" onClick={() => { setIndex((index + 1) % flashcards.length); setFlipped(false) }}>Next &nbsp; â†’</Button></div></div></> }
function QuizzesPage() { const [selected, setSelected] = useState(''); const [question, setQuestion] = useState(1); const options = ['A linked list', 'A binary tree', 'A hash table', 'A queue']; return <><PageTitle eyebrow="Check your understanding" title="Quizzes" text="A little practice goes a long way." /><section className="quiz-card"><div className="quiz-top"><span>Data Structures</span><strong>Question {question} of 10</strong></div><ProgressBar value={question * 10} /><p className="dash-eyebrow">QUESTION {question}</p><h2>Which data structure follows the LIFO principle?</h2><div className="answer-options">{options.map((option, i) => <button className={selected === option ? 'selected' : ''} onClick={() => setSelected(option)} key={option}><span>{String.fromCharCode(65 + i)}</span>{option}</button>)}</div><div className="quiz-footer"><small>{selected ? 'Answer selected' : 'Choose an answer to continue'}</small><Button onClick={() => { setQuestion(question === 10 ? 1 : question + 1); setSelected('') }}>Next Question â†’</Button></div></section></> }
function PlannerPage() { return <><PageTitle eyebrow="Plan with purpose" title="Study Planner" text="A simple plan for a more consistent learning rhythm." action={<Button>+ &nbsp; Add Study Task</Button>} /><section className="dashboard-panel planner-panel"><div className="planner-date"><span>Today</span><strong>Tuesday, October 15</strong></div><div className="planner-list">{plans.map(([topic, time, status], i) => <div className="planner-item" key={topic}><button className={`checkbox ${i === 0 ? 'checked' : ''}`}>{i === 0 && 'âœ“'}</button><div><strong>{topic}</strong><small>{time} Â· {i === 0 ? 'Computer Science' : 'Database Management'}</small></div><span className={`status ${status.toLowerCase().replace(' ', '-')}`}>{status}</span></div>)}</div></section></> }
function ChatPage() { const [message, setMessage] = useState(''); return <><PageTitle eyebrow="Your study sidekick" title="LearnMate AI Assistant" text="Ask questions, explore ideas, and get unstuck." /><section className="chat-panel"><div className="chat-messages"><div className="chat-message ai"><span className="chat-avatar">L</span><div><strong>LearnMate AI</strong><p>Hi! I'm your LearnMate AI study assistant. How can I help you learn today?</p></div></div><div className="chat-message user"><div><strong>You</strong><p>Can you explain the difference between a stack and a queue?</p></div></div><div className="chat-message ai"><span className="chat-avatar">L</span><div><strong>LearnMate AI</strong><p>Of course. A stack is LIFO: the last item added is the first removed. A queue is FIFO: the first item added is the first removed.</p></div></div></div><form className="chat-input" onSubmit={(event) => event.preventDefault()}><input value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Ask me anything about your studies..." /><button type="submit">Send â†—</button></form></section></> }
function ProgressPage() { return <><PageTitle eyebrow="See your momentum" title="Progress" text="Small steps add up. Here is how your learning is moving." /><div className="stats-grid"><StatCard icon="â†—" label="Overall progress" value="78%" detail="+12% this month" tone="coral" /><StatCard icon="âœ“" label="Quiz performance" value="82%" detail="Across 8 quizzes" tone="mint" /><StatCard icon="â—·" label="Study hours" value="24h" detail="This month" tone="yellow" /><StatCard icon="âœ¦" label="Topics completed" value="18" detail="3 this week" tone="blue" /></div><div className="progress-grid"><section className="dashboard-panel"><div className="panel-header"><div><p className="dash-eyebrow">This month</p><h2>Learning progress</h2></div></div><div className="big-progress"><strong>78%</strong><ProgressBar value={78} /><small>12% more than last month</small></div></section><section className="dashboard-panel activity-panel"><div className="panel-header"><div><p className="dash-eyebrow">Keep going</p><h2>Recent activity</h2></div></div>{['Completed Data Structures quiz', 'Uploaded Database notes', 'Mastered 3 flashcards'].map((item, i) => <div className="activity-item" key={item}><span className={`activity-dot dot-${i}`} /><div><strong>{item}</strong><small>{i + 1} day{i ? 's' : ''} ago</small></div></div>)}</section></div></> }
function SettingsPage() { return <><PageTitle eyebrow="Make it yours" title="Settings" text="Manage your profile and learning preferences." /><section className="settings-panel"><div className="settings-section"><h2>Profile information</h2><div className="form-grid"><label>Full name<input defaultValue="Student" /></label><label>Email address<input defaultValue="student@learnmate.ai" /></label></div></div><div className="settings-section"><h2>Display preferences</h2><label className="toggle-row"><span><strong>Compact dashboard</strong><small>Show more items with less spacing</small></span><input type="checkbox" /></label></div><div className="settings-section"><h2>Notification preferences</h2><label className="toggle-row"><span><strong>Study reminders</strong><small>Get a gentle nudge when it is time to study</small></span><input type="checkbox" defaultChecked /></label></div><Button>Save Changes</Button></section></> }

function Dashboard({ onHome, onLogout }) { const [page, setPage] = useState('Dashboard'); const [mobileOpen, setMobileOpen] = useState(false); const navigate = (next) => { if (next === 'Logout') { localStorage.removeItem('learnmateToken'); onLogout(); return } setPage(next); setMobileOpen(false) }; const pages = { Dashboard: <Overview navigate={navigate} />, 'My Notes': <NotesPage />, 'Upload Notes': <UploadPage />, Summaries: <SummariesPage />, Flashcards: <FlashcardsPage />, Quizzes: <QuizzesPage />, 'Study Planner': <PlannerPage />, 'AI Chat': <ChatPage />, Progress: <ProgressPage />, Settings: <SettingsPage /> }; return <div className="dashboard-shell"><aside className={`sidebar ${mobileOpen ? 'open' : ''}`}><div className="sidebar-top"><DashboardLogo onHome={onHome} /><button className="close-sidebar" onClick={() => setMobileOpen(false)}>Ã—</button></div><p className="side-label">Workspace</p><div className="sidebar-nav">{navItems.map(([icon, label]) => <button className={page === label ? 'selected' : ''} onClick={() => navigate(label)} key={label}><span>{icon}</span>{label}</button>)}</div><div className="sidebar-bottom"><div className="profile-mini"><span>ST</span><div><strong>Student</strong><small>Free account</small></div><span className="more-dots">â€¢â€¢â€¢</span></div></div></aside>{mobileOpen && <button className="sidebar-overlay" onClick={() => setMobileOpen(false)} aria-label="Close menu" />}<div className="dashboard-main"><header className="dashboard-header"><button className="open-sidebar" onClick={() => setMobileOpen(true)} aria-label="Open menu">â˜°</button><div className="breadcrumb">Workspace <span>/</span> <strong>{page}</strong></div><div className="header-actions"><button className="header-icon" aria-label="Notifications">â™§</button><button className="header-avatar">ST</button></div></header><main className="dashboard-content">{pages[page]}</main></div></div> }

export default Dashboard

